plugin:
    name: 'awebsome.serverpilot::lang.plugin.name'
    description: 'awebsome.serverpilot::lang.plugin.description'
    author: LucasZdv
    icon: oc-icon-cloud
    homepage: 'https://awebsome.me'

navigation:
    serverpilot:
        label: ServerPilot
        url: awebsome/serverpilot/apps
        icon: icon-cloud
        permissions:
            - awebsome.serverpilot.serverpilot
        order: '500'
        sideMenu:
            apps:
                label: Apps
                url: awebsome/serverpilot/apps
                icon: icon-puzzle-piece
                permissions:
                    - awebsome.serverpilot.apps
            databases:
                label: Databases
                url: awebsome/serverpilot/databases
                icon: icon-database
                permissions:
                    - awebsome.serverpilot.databases
            sysusers:
                label: System Users
                url: awebsome/serverpilot/sysusers
                icon: icon-user-secret
                permissions:
                    - awebsome.serverpilot.sysusers
            servers:
                label: Servers
                url: awebsome/serverpilot/servers
                icon: icon-server
                permissions:
                    - awebsome.serverpilot.servers
            actions:
                label: Actions
                url: awebsome/serverpilot/actions
                icon: icon-fire
                permissions:
                    - awebsome.serverpilot.actions
permissions:
    awebsome.serverpilot.serverpilot:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'Can use Awebsome ServerPilot'
    awebsome.serverpilot.actions:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'View actions log'
    awebsome.serverpilot.servers:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'View Servers'
    awebsome.serverpilot.sysusers:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'Manage Sysusers'
    awebsome.serverpilot.databases:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'Manage Databases'
    awebsome.serverpilot.apps:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'Manage Apps'
    awebsome.serverpilot.settings:
        tab: 'awebsome.serverpilot::lang.plugin.name'
        label: 'ServerPilot Settings'
